// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAM6UA9vjZ0kPfFxwN4mh09Dl5YONaCxKE',
    appId: '1:897557681780:web:364fa6ed8a5506279b2321',
    messagingSenderId: '897557681780',
    projectId: 'push-notifications-271fd',
    authDomain: 'push-notifications-271fd.firebaseapp.com',
    storageBucket: 'push-notifications-271fd.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsCIGhfP22oumfY4XAwbOw5-7GEOW-7rQ',
    appId: '1:897557681780:android:c9783b6a5fa9d7499b2321',
    messagingSenderId: '897557681780',
    projectId: 'push-notifications-271fd',
    storageBucket: 'push-notifications-271fd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgdOQNq2JDtRTGbDyl7139mo1UMAW_wLc',
    appId: '1:897557681780:ios:51db8d4815cf3b5f9b2321',
    messagingSenderId: '897557681780',
    projectId: 'push-notifications-271fd',
    storageBucket: 'push-notifications-271fd.firebasestorage.app',
    iosBundleId: 'com.example.firebaseNotifications',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgdOQNq2JDtRTGbDyl7139mo1UMAW_wLc',
    appId: '1:897557681780:ios:51db8d4815cf3b5f9b2321',
    messagingSenderId: '897557681780',
    projectId: 'push-notifications-271fd',
    storageBucket: 'push-notifications-271fd.firebasestorage.app',
    iosBundleId: 'com.example.firebaseNotifications',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAM6UA9vjZ0kPfFxwN4mh09Dl5YONaCxKE',
    appId: '1:897557681780:web:fcea1e64b54710f99b2321',
    messagingSenderId: '897557681780',
    projectId: 'push-notifications-271fd',
    authDomain: 'push-notifications-271fd.firebaseapp.com',
    storageBucket: 'push-notifications-271fd.firebasestorage.app',
  );
}
